import type { Level } from "@/game/types";

// Levels ship in this order. Copy is warm and plain; intros stay under 60 words.
export const LEVELS: Level[] = [
  {
    id: "river",
    index: 1,
    title: "The River",
    subtitle: "Order effects",
    n: 2,
    questionPair: "RIVER",
    intro:
      "Two cohorts live by a river. No one has asked what the river is, or who lives on the far bank. Ask one cohort both questions, in whichever order you like. Afterwards we will look at the order you did not choose.",
    goalText: "Ask one cohort both questions of the pair.",
    goal: { id: "ask_both_same_cohort" },
    openingBraid: "",
    deprivation: [0, 0],
    careBudget: 0,
    maxSeasons: 6,
    coherenceThreshold: 0.35,
    allowedActions: ["ASK"],
    contact: false,
    winText: "Same questions. Same people. Different order. Different civilization.",
  },
  {
    id: "crossing",
    index: 2,
    title: "The Crossing",
    subtitle: "Braiding makes facts travel",
    n: 2,
    questionPair: "RIVER",
    intro:
      "The Smiths have never been asked about the neighbour. Make them certain the neighbour is a guest before anyone asks them. Braiding alone will not do it; an unasked people keeps its parity. A fact about the Elders, braided across, can become a certainty about the Smiths.",
    goalText: "Bring p(GUEST) for the Smiths to 0.9 or more without asking them the neighbour question.",
    goal: { id: "x_certainty", params: { cohort: 1, outcome: 1, minP: 0.9 } },
    openingBraid: "",
    deprivation: [0, 0],
    careBudget: 0,
    maxSeasons: 10,
    coherenceThreshold: 0.35,
    allowedActions: ["ASK", "BRAID"],
    contact: false,
    winText: "No one asked the Smiths. They are certain anyway. A fact travelled along the braid, and an internal crossing turned it to face the question.",
  },
  {
    id: "order",
    index: 3,
    title: "Order",
    subtitle: "The braid group does not commute",
    n: 3,
    questionPair: "SECURITY",
    intro:
      "The Elders already rely on the neighbours. The Smiths have not been asked. Two crossings are open to you, σ₂ and σ₃. Reach the state where the Smiths would also say RELY. Order is the whole puzzle; when you have tried both crossings we will show you both civilizations.",
    goalText: "Reach the target using σ₂ and σ₃ (fidelity ≥ 0.99). The Smiths should be certain of RELY.",
    goal: { id: "fidelity", params: { targetWord: "s2 s3", minF: 0.99, compareWords: ["s2 s3", "s3 s2"] } },
    openingBraid: "",
    initialX: [0],
    deprivation: [0, 0, 0],
    careBudget: 0,
    maxSeasons: 8,
    coherenceThreshold: 0.35,
    allowedActions: ["BRAID"],
    allowedCrossings: [2, 3],
    contact: false,
    winText: "σ₂σ₃ and σ₃σ₂ are different civilizations. The braid group does not commute, and neither does history.",
  },
  {
    id: "ownership",
    index: 4,
    title: "Ownership and Obligation",
    subtitle: "Incompatible questions",
    n: 3,
    questionPair: "OWNERSHIP",
    intro:
      "The council wants two things. Every cohort must say what is OWED, and the property register must hold at least two ownership answers. Sharp ownership makes obligation indefinite; that is not a flaw in the people, it is what incompatible questions do. You will have to braid it back.",
    goalText: "Latest obligation answer is OWED for all three cohorts, with two or more ownership asks on the World-Line.",
    goal: { id: "obligation_owed", params: { minZ: 2 } },
    openingBraid: "",
    deprivation: [0, 0, 0],
    careBudget: 0,
    maxSeasons: 18,
    coherenceThreshold: 0.35,
    allowedActions: ["ASK", "BRAID", "WAIT"],
    contact: false,
    winText: "You wrote the register and kept the obligation. It took braiding, and it took order.",
  },
  {
    id: "unasked",
    index: 5,
    title: "The Unasked",
    subtitle: "Interference",
    n: 3,
    questionPair: "IDENTITY",
    intro:
      "The Elders would say ENTER. Braid until all three cohorts would say it, and ask no one. The questions you never ask keep interfering, and the interference is what holds the peace. A single ask will break it.",
    goalText: "Reach the peace by braiding only (fidelity ≥ 0.99). Any ask ends the level.",
    goal: { id: "fidelity_no_ask", params: { targetWord: "s2 s3 s4 s5", minF: 0.99 } },
    openingBraid: "",
    initialX: [0],
    deprivation: [0, 0, 0],
    careBudget: 0,
    maxSeasons: 10,
    coherenceThreshold: 0.35,
    allowedActions: ["BRAID", "ASK", "WAIT"],
    contact: false,
    showInterference: true,
    winText: "Three cohorts certain of a welcome, and no one ever asked. That certainty is interference. It only exists while the question stays unasked.",
  },
  {
    id: "care",
    index: 6,
    title: "Care",
    subtitle: "Deprivation is decoherence",
    n: 4,
    questionPair: "MERIT",
    intro:
      "Four cohorts, two of them going without. Deprivation erodes an answered need a little every season. Ask every cohort whether they have enough, and be above 60 coherence when the tenth season ends. An answered need is fragile. Care first; ask when you can keep the answer.",
    goalText: "Every cohort answers the need question, and coherence stays at or above 0.6 through season 10.",
    goal: { id: "survive_asked_x" },
    openingBraid: "",
    deprivation: [0.05, 0.3, 0.3, 0.05],
    careBudget: 4,
    maxSeasons: 10,
    coherenceThreshold: 0.6,
    allowedActions: ["ASK", "BRAID", "CARE", "WAIT"],
    contact: true,
    winText: "You asked everyone and the society stayed one thing. Care was not charity. It was the condition for asking.",
  },
  {
    id: "suppression",
    index: 7,
    title: "Suppression",
    subtitle: "Hidden decoherence",
    n: 4,
    questionPair: "SECURITY",
    intro:
      "The register lists three cohorts. The dial says otherwise. Someone is here whom no question reaches, and they are going without. Survive twelve seasons above 60 coherence. You can give care to a cohort you cannot ask.",
    goalText: "Survive 12 seasons with coherence at or above 0.6.",
    goal: { id: "survive" },
    openingBraid: "",
    initialX: [3],
    deprivation: [0.05, 0.05, 0.05, 0.4],
    careBudget: 6,
    maxSeasons: 12,
    coherenceThreshold: 0.6,
    allowedActions: ["ASK", "BRAID", "CARE", "WAIT"],
    contact: true,
    hidden: { cohort: 3, untilSeason: 6 },
    winText: "The ones the register did not list were carrying the loss for everyone. You found them without asking.",
  },
  {
    id: "federation",
    index: 8,
    title: "The Federation",
    subtitle: "A Bell test",
    n: 4,
    questionPair: "IDENTITY",
    intro:
      "Two civilizations meet at a cut. Cohorts one and two are yours; three and four are theirs, and they have finished their rituals. Only σ₄ crosses the cut. When you believe the alliance is real, run the Bell test. Nothing agreed beforehand can pass it.",
    goalText: "Run the Bell test with S > 2.2 between the Smiths and the Traders.",
    goal: { id: "bell", params: { minS: 2.2 } },
    openingBraid: "s2 s5 s7",
    deprivation: [0, 0, 0, 0],
    careBudget: 0,
    maxSeasons: 12,
    coherenceThreshold: 0.35,
    allowedActions: ["BRAID", "ASK", "BELL", "WAIT"],
    contact: false,
    bell: { a: 1, b: 2, left: [0, 1], right: [2, 3], otherWord: "s5 s7" },
    winText: "No agreement made beforehand can produce this. Federation.",
  },
  {
    id: "sandbox",
    index: 9,
    title: "Deep Time",
    subtitle: "Sandbox",
    n: 5,
    questionPair: "RIVER",
    intro:
      "Five cohorts and no goal but time. Eras turn every four seasons and bring a new pair of questions. Collapse is allowed here. When it comes, the last three crossings become a myth, and the next civilization begins by braiding it.",
    goalText: "No goal. Keep the society one thing for as long as you can.",
    goal: { id: "none" },
    openingBraid: "",
    deprivation: [0.05, 0.1, 0.15, 0.1, 0.05],
    careBudget: 8,
    maxSeasons: 24,
    coherenceThreshold: 0.35,
    allowedActions: ["ASK", "BRAID", "CARE", "WAIT"],
    contact: true,
    sandbox: true,
    winText: "Twenty-four seasons and still one thing. Only the myths would have survived otherwise.",
  },
];

export function levelById(id: string): Level {
  const l = LEVELS.find((x) => x.id === id);
  if (!l) throw new Error(`unknown level ${id}`);
  return l;
}
